services:
  plex:
    image: lscr.io/linuxserver/plex:docker
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /Media/appdata/plex:/config
      - /Media/seris:/tv
      - /Media/movies:/movies
      - /Media:/mymedia
    restart: unless-stopped
